USE KOTDESA
GO

/****** Object:  Table [KOTINFO].[CLIENTES]    Script Date: 26/12/2017 12:04:31 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
--CREATE SCHEMA KOTINFO

CREATE TABLE [CLIENTES](
	[ID_CLIENTE] NUMERIC(18,0) IDENTITY PRIMARY KEY,
	[COD_CLIENTE] [numeric](18, 0) NULL,
    [ID_TIPO_CLIENTE] [numeric](18, 0) NULL,
	[NOMBRE] [nvarchar](255) NULL,
	[APELLIDO] [nvarchar](255) NULL,
	[EMAIL][nvarchar](255) NULL,
	[TELEFONO] [nvarchar](255) NULL,
	[CELULAR] [nvarchar](255) NULL,
	[OTRO_TEL] [nvarchar](255) NULL,
	[DNI] [nvarchar](255) NULL,
	[ID_TIPO_CUIL_CUIT] [numeric](18, 0) NULL,
	[FECHA_NACIMIENTO] [nvarchar](255) NULL,
	[DOMICILIO_CALLE] [nvarchar](255) NULL,
	[DOMICILIO_ALTURA] [nvarchar](255) NULL,
	[DOMICILIO_PISO] [nvarchar](255) NULL,
	[DOMICILIO_DPTO] [nvarchar](255) NULL,
	[DOMICILIO_PROVINCIA] [nvarchar](255) NULL,
	[DOMICILIO_PARTIDO] [nvarchar](255) NULL,
	[DOMICILIO_LOCALIDAD] [nvarchar](255) NULL,
	[OBSERVACIONES] [nvarchar](max) NULL,
	)
GO

Create TABLE [PENDIENTES](
	[ID_PENDIENTE] NUMERIC(18,0) IDENTITY PRIMARY KEY,
	[COD_PENDIENTE] NUMERIC(18,0) UNIQUE,
	[ID_CLIENTE] [numeric](18, 0) NULL,
	[CONCEPTO] [nvarchar](255) NULL,
	[PERIODO] [nvarchar](255) NULL,
	[FECHA] [nvarchar](255) NULL,
	[DIRECCION][nvarchar](255) NULL,
	[IMPORTE] [numeric](18, 2) NULL,
	[PAGADO]  BIT DEFAULT 0,
	[OBSERVACIONES] [nvarchar](255) NULL
	)
GO


CREATE TABLE [TIPO_CLIENTES] (
	[ID_TIPO_CLIENTE] NUMERIC(18,0) IDENTITY PRIMARY KEY,
    [DESCRIPCION] [nvarchar](255) NULL,
	)
GO

CREATE TABLE [TIPO_CUIL_CUIT] (
	[ID_TIPO_CUIL_CUIT] NUMERIC(18,0) IDENTITY PRIMARY KEY,
    [DESCRIPCION] [nvarchar](255) NULL,
	)
GO

CREATE PROCEDURE [SP_INSERTAR_CLIENTE]
		@nombre NVARCHAR(255) = null,
		@apellido NVARCHAR(255) = null,
		@email NVARCHAR(255) = null,
		@telefono NVARCHAR(255) = null,
		@celular NVARCHAR(255) = null,
		@otro_tel NVARCHAR(255) = null,
		@id_tipo_cliente NUMERIC(18,0) = 1,
		@id_tipo_cuil_cuit NUMERIC(18,0) = 1,
		@dni NVARCHAR(255) NULL,
		@fecha_nacimiento NVARCHAR(255) = null,
		@domicilio_calle NVARCHAR(255) = null,
		@domicilio_altura NVARCHAR(255) = null,
		@domicilio_piso NVARCHAR(255) = null,
		@domicilio_dpto NVARCHAR(255) = null,
		@domicilio_provincia NVARCHAR(255) = null,
		@domicilio_partido NVARCHAR(255) = null,
		@domicilio_localidad NVARCHAR(255) = null,
		@observaciones NVARCHAR(255) = null
		AS
		BEGIN
		SET NOCOUNT ON;
		DECLARE	@cod_cliente numeric(18,0)
		SET @cod_cliente= (SELECT COUNT(*) FROM dbo.CLIENTES)
		INSERT INTO dbo.CLIENTES(COD_CLIENTE, NOMBRE, APELLIDO, EMAIL, TELEFONO, CELULAR, OTRO_TEL, ID_TIPO_CLIENTE, ID_TIPO_CUIL_CUIT, DNI, FECHA_NACIMIENTO, DOMICILIO_CALLE,DOMICILIO_ALTURA,DOMICILIO_PISO,DOMICILIO_DPTO,DOMICILIO_PROVINCIA,DOMICILIO_PARTIDO,DOMICILIO_LOCALIDAD,OBSERVACIONES)
		VALUES(@cod_cliente,@nombre,@apellido, @email,@telefono,@celular,@otro_tel, @id_tipo_cliente, @id_tipo_cuil_cuit,@dni,@fecha_nacimiento,@domicilio_calle,@domicilio_altura,@domicilio_piso,@domicilio_dpto,@domicilio_provincia,@domicilio_partido,@domicilio_localidad, @observaciones   )
		END
GO

CREATE PROCEDURE [SP_INSERTAR_PENDIENTE]
	@id_cliente NUMERIC(18,0),
	@concepto NVARCHAR(255) = null,
	@periodo NVARCHAR(255) = null,
	@fecha NVARCHAR(255) = null,
	@direccion NVARCHAR(255) = null,
	@importe [numeric](18, 2) = null,
	@pagado BIT,
	@observaciones NVARCHAR(255) = null
		AS
		BEGIN
		SET NOCOUNT ON;
		DECLARE	@cod_pendiente numeric(18,0)
		SET @cod_pendiente= (SELECT COUNT(*) FROM dbo.PENDIENTES)
		INSERT INTO dbo.PENDIENTES(ID_CLIENTE, COD_PENDIENTE, CONCEPTO, PERIODO, FECHA, DIRECCION, IMPORTE, PAGADO, OBSERVACIONES)
		VALUES(@id_cliente, @cod_pendiente, @concepto, @periodo, @fecha, @direccion, @importe, @pagado, @observaciones)
		END
GO

CREATE PROCEDURE [SP_TRAER_TIPO_CLIENTES]
		AS
		BEGIN
		SET NOCOUNT ON;
		SELECT * FROM DBO.TIPO_CLIENTES
		END
GO

CREATE PROCEDURE [SP_TRAER_TIPO_CUIL_CUIT]
		AS
		BEGIN
		SET NOCOUNT ON;
		SELECT * FROM DBO.TIPO_CUIL_CUIT
		END
GO

CREATE PROCEDURE [SP_TRAER_PROVINCIAS]
		AS
		BEGIN
		SET NOCOUNT ON;
		SELECT ID_PROVINCIA,NOMBRE FROM DBO.PROVINCIAS
		ORDER BY NOMBRE ASC
		END
GO

CREATE PROCEDURE [SP_TRAER_DEPARTAMENTOS_POR_PROVINCIA]
	@id_provincia NUMERIC(18,0)
	AS
		BEGIN
		SET NOCOUNT ON;
		SELECT ID_DEPARTAMENTO,NOMBRE FROM DBO.DEPARTAMENTOS 
		WHERE ID_PROVINCIA = @id_provincia 
		ORDER BY PESO ASC,NOMBRE ASC
	END
GO

CREATE PROCEDURE [SP_TRAER_LOCALIDAD_POR_DEPARTAMENTO]
	@id_departamento NUMERIC(18,0)
	AS
	BEGIN
		SET NOCOUNT ON;
		SELECT ID_LOCALIDAD,NOMBRE FROM DBO.LOCALIDADES
		WHERE ID_DEPARTAMENTO = @id_departamento 
		ORDER BY PESO ASC,NOMBRE ASC
	END
GO

CREATE PROCEDURE [SP_TRAER_CLIENTES]
	AS
		BEGIN
		SELECT ID_CLIENTE, APELLIDO FROM DBO.CLIENTES ORDER BY APELLIDO ASC
		END
GO

CREATE PROCEDURE [SP_TRAER_CLIENTES_APELLIDO_Y_NOMBRE]
	AS
		BEGIN
		SELECT ID_CLIENTE, (''+APELLIDO+', '+NOMBRE) AS APELLIDO FROM DBO.CLIENTES ORDER BY APELLIDO ASC
		END
GO

CREATE PROCEDURE [SP_TRAER_CLIENTE_POR_ID]
	@id_cliente NUMERIC(18,0)
	AS
	BEGIN
		SET NOCOUNT ON;
		SELECT * FROM DBO.CLIENTES
		WHERE ID_CLIENTE = @id_cliente
	END
GO

CREATE PROCEDURE [SP_TRAER_CLIENTE_POR_COD]
	@cod_cliente NUMERIC(18,0)
	AS
	BEGIN
		SET NOCOUNT ON;
		SELECT * FROM DBO.CLIENTES
		WHERE COD_CLIENTE = @cod_cliente
	END
GO

CREATE PROCEDURE [SP_TRAER_TODOS_LOS_PENDIENTES]
	AS
	BEGIN
	SET NOCOUNT ON;
		SELECT CLIENTES.APELLIDO, PENDIENTES.CONCEPTO,PENDIENTES.IMPORTE, PENDIENTES.PAGADO
		FROM DBO.PENDIENTES INNER JOIN DBO.CLIENTES 
		ON PENDIENTES.ID_CLIENTE = CLIENTES.ID_CLIENTE
	END
GO

CREATE PROCEDURE [SP_TRAER_PENDIENTES_POR_CLIENTE_ID]
	@id_cliente NUMERIC(18,0),
	@pagado BIT = null
	AS
	BEGIN
	SET NOCOUNT ON;
		SELECT PENDIENTES.ID_PENDIENTE, PENDIENTES.COD_PENDIENTE,CLIENTES.APELLIDO,  PENDIENTES.CONCEPTO, PENDIENTES.PERIODO, PENDIENTES.FECHA, PENDIENTES.DIRECCION, PENDIENTES.IMPORTE, PENDIENTES.PAGADO, PENDIENTES.OBSERVACIONES
		FROM PENDIENTES INNER JOIN CLIENTES 
		ON PENDIENTES.ID_CLIENTE = CLIENTES.ID_CLIENTE
		WHERE CLIENTES.ID_CLIENTE = @id_cliente AND
		 (@pagado IS NULL OR pendientes.pagado = @pagado) 
	END
GO



CREATE PROCEDURE [SP_TRAER_PENDIENTE_POR_CODIGO]
	@cod_pendiente NUMERIC(18,0)
	AS
	BEGIN
	SET NOCOUNT ON;
		SELECT CLIENTES.ID_CLIENTE, (''+CLIENTES.APELLIDO+', '+CLIENTES.NOMBRE) AS APELLIDO, PENDIENTES.ID_PENDIENTE, PENDIENTES.COD_PENDIENTE, PENDIENTES.CONCEPTO, PENDIENTES.PERIODO, PENDIENTES.FECHA, PENDIENTES.DIRECCION, PENDIENTES.IMPORTE, PENDIENTES.PAGADO, PENDIENTES.OBSERVACIONES
		FROM DBO.PENDIENTES INNER JOIN DBO.CLIENTES 
		ON PENDIENTES.ID_CLIENTE = CLIENTES.ID_CLIENTE
		WHERE PENDIENTES.COD_PENDIENTE = @cod_pendiente
	END
GO


CREATE PROCEDURE [SP_ACTUALIZAR_CLIENTE_POR_ID]
	@id_cliente NUMERIC(18,0),
	@nombre NVARCHAR(255) = null,
	@apellido NVARCHAR(255) = null,
	@email NVARCHAR(255) = null,
	@telefono NVARCHAR(255) = null,
	@celular NVARCHAR(255) = null,
	@otro_tel NVARCHAR(255) = null,
	@id_tipo_cliente NUMERIC(18,0) = 1,
	@id_tipo_cuil_cuit NUMERIC(18,0) = 1,
	@dni NVARCHAR(255) NULL,
	@fecha_nacimiento NVARCHAR(255) = null,
	@domicilio_calle NVARCHAR(255) = null,
	@domicilio_altura NVARCHAR(255) = null,
	@domicilio_piso NVARCHAR(255) = null,
	@domicilio_dpto NVARCHAR(255) = null,
	@domicilio_provincia NVARCHAR(255) = null,
	@domicilio_partido NVARCHAR(255) = null,
	@domicilio_localidad NVARCHAR(255) = null,
	@observaciones NVARCHAR(255) = null
	AS
	BEGIN
	UPDATE  DBO.CLIENTES
	SET NOMBRE=@nombre, APELLIDO=@apellido, EMAIL=@email, TELEFONO=@telefono, CELULAR=@celular, OTRO_TEL=@otro_tel, ID_TIPO_CLIENTE=@id_tipo_cliente, ID_TIPO_CUIL_CUIT=@id_tipo_cuil_cuit, DNI=@dni, FECHA_NACIMIENTO=@fecha_nacimiento, DOMICILIO_CALLE=@domicilio_calle,DOMICILIO_ALTURA=@domicilio_altura,DOMICILIO_PISO=@domicilio_piso,DOMICILIO_DPTO=@domicilio_dpto,DOMICILIO_PROVINCIA=@domicilio_provincia,DOMICILIO_PARTIDO=@domicilio_partido,DOMICILIO_LOCALIDAD=@domicilio_localidad,OBSERVACIONES=@observaciones
	WHERE ID_CLIENTE=@id_cliente
	END
GO

CREATE PROCEDURE [SP_ACTUALIZAR_PENDIENTE_POR_ID_PENDIENTE]
	@id_pendiente NUMERIC(18,0),
	@concepto NVARCHAR(255) = null,
	@periodo NVARCHAR(255) = null,
	@fecha NVARCHAR(255) = null,
	@direccion NVARCHAR(255) = null,
	@importe [numeric](18, 2) = null,
	@pagado BIT,
	@observaciones NVARCHAR(255) = null
	AS
	BEGIN
	UPDATE  PENDIENTES
	SET 
	CONCEPTO= IsNull(@concepto, concepto), 
	PERIODO= IsNull(@periodo, periodo), 
	FECHA= IsNull(@fecha, fecha), 
	DIRECCION= IsNull(@direccion, direccion), 
	IMPORTE= IsNull(@importe, importe),
	PAGADO= IsNull(@pagado, pagado),
	OBSERVACIONES= IsNull(@observaciones, observaciones)
	WHERE  ID_PENDIENTE = @id_pendiente
	END
GO



INSERT INTO dbo.TIPO_CLIENTES (DESCRIPCION)
VALUES ('<Vacio>'),('Dueño'),('Inquilino'),('Comprador'),('Vendedor'),('Contacto'),('Escribania');

GO

INSERT INTO dbo.TIPO_CUIL_CUIT (DESCRIPCION)
VALUES ('<CUIL/CUIT>'),('CUIL'),('CUIT');

GO
ALTER TABLE CLIENTES ADD CONSTRAINT FK_TIPO_CLIENTES_CLIENTES_ID_TIPO_CLIENTES
	FOREIGN KEY (ID_TIPO_CLIENTE) REFERENCES dbo.TIPO_CLIENTES(ID_TIPO_CLIENTE)

GO


ALTER TABLE CLIENTES ADD CONSTRAINT FK_TIPO__CUIL_CUIT_TIPO_CUIL_CUIT_ID_TIPO__CUIL_CUIT
	FOREIGN KEY (ID_TIPO_CUIL_CUIT) REFERENCES dbo.TIPO_CUIL_CUIT(ID_TIPO_CUIL_CUIT)

GO


ALTER TABLE PENDIENTES ADD CONSTRAINT FK_ID_CLIENTE_PENDIENTES_ID_CLIENTE
	FOREIGN KEY (ID_CLIENTE) REFERENCES dbo.CLIENTES(ID_CLIENTE)

GO




drop table CLIENTES
INSERT INTO dbo.CLIENTES  (COD_CLIENTE, NOMBRE)
VALUES (1,  '')



select * from CLIENTES

/*

ALTER TABLE CLIENTES DROP CONSTRAINT FK_TIPO_CLIENTES_CLIENTES_ID_TIPO_CLIENTES
GO
ALTER TABLE CLIENTES DROP CONSTRAINT FK_TIPO__CUIL_CUIT_TIPO_CUIL_CUIT_ID_TIPO__CUIL_CUIT
GO
ALTER TABLE PENDIENTES DROP CONSTRAINT  FK_ID_CLIENTE_PENDIENTES_ID_CLIENTE
GO
DROP TABLE [PENDIENTES]
GO
DROP TABLE  [CLIENTES]
GO
DROP TABLE  [TIPO_CLIENTES]
GO
DROP TABLE  [TIPO_CUIL_CUIT]
GO
DROP PROCEDURE [SP_INSERTAR_CLIENTE]
GO
DROP PROCEDURE [SP_INSERTAR_PENDIENTE]
GO
DROP PROCEDURE [SP_TRAER_TIPO_CLIENTES]
GO
DROP PROCEDURE [SP_TRAER_TIPO_CUIL_CUIT]
GO
DROP PROCEDURE [SP_TRAER_PROVINCIAS]
GO
DROP PROCEDURE [SP_TRAER_DEPARTAMENTOS_POR_PROVINCIA]
GO
DROP PROCEDURE [SP_TRAER_CLIENTES]
GO
DROP PROCEDURE [SP_TRAER_CLIENTE_POR_ID]
GO
DROP PROCEDURE [SP_ACTUALIZAR_CLIENTE_POR_ID]
GO
DROP PROCEDURE [SP_TRAER_CLIENTE_POR_COD]
GO
DROP PROCEDURE [SP_TRAER_CLIENTES_APELLIDO_Y_NOMBRE]
GO
DROP PROCEDURE [SP_TRAER_TODOS_LOS_PENDIENTES]
GO
DROP PROCEDURE [SP_TRAER_PENDIENTES_POR_CLIENTE_ID]
GO
DROP PROCEDURE [SP_TRAER_PENDIENTES_CODIGO]
GO
DROP PROCEDURE [SP_ACTUALIZAR_PENDIENTE_POR_ID_PENDIENTE]
*/
 
 exec [SP_TRAER_CLIENTE_POR_ID] 1
  exec SP_TRAER_PROVINCIAS

 SELECT * FROM TIPO_CLIENTES

 SELECT *  FROM PENDIENTES

 		SELECT ID_DEPARTAMENTO,NOMBRE,PESO FROM DBO.DEPARTAMENTOS 
		WHERE ID_PROVINCIA = 1
		ORDER BY PESO, NOMBRE ASC

		select * from CLIENTES

CREATE PROCEDURE [SP_TRAER_CLIENTE_POR_ID]
	@id_cliente NUMERIC(18,0)
	AS

UPDATE Customers
SET ContactName = 'Alfred Schmidt', City= 'Frankfurt'
WHERE CustomerID = 1;


USE master
SELECT * FROM DBO.CLIENTES
drop table TIPO_CLIENTES

DELETE FROM DBO.CLIENTES
WHERE ID_CLIENTE=1

select * from PENDIENTES

EXECUTE SP_TRAER_PENDIENTE_POR_CODIGO 4
select * FROM CLIENTES
SELECT CLIENTES.APELLIDO, PENDIENTES.CONCEPTO,PENDIENTES.IMPORTE, PENDIENTES.PAGADO FROM PENDIENTES INNER JOIN CLIENTES ON PENDIENTES.ID_CLIENTE = CLIENTES.ID_CLIENTE